### ISSUE TITLE
极空间更新最新版本后所有都显示没有更新，实际有更新

### ISSUE THREAD

**Issue by denglinfu** [onlyLTY/oneKeyUpdate#68]
版本是最新的 2.04
已经设置了代理，在 portainer 中可以正常拉取镜像
日志有对应错误提示
![image](https://github.com/user-attachments/assets/fa1d5236-7b5f-49e0-a859-a472a9de36ba)
![image](https://github.com/user-attachments/assets/f09f9d26-970f-42b3-83c6-202595199662)

补充一下，虽然没有提示更新，但是如果点击更新也会将制定的 docker 更新到最新版

**Comment by lovemikusama** [comment]
环境变量设置HTTP_PROXY和HTTPS_PROXY就可以(我用的mihomo)，刚刚测试了(UGOS PRO compose模式)，如果只设置HTTP_PROXY就不行。
![截图20240926170240](https://github.com/user-attachments/assets/6d3271d5-1771-43f3-9256-5f1bbe3fd133)

**Comment by chong206** [comment]
> 环境变量设置HTTP_PROXY和HTTPS_PROXY就可以（我用的mihomo），刚刚测试了（UGOS PRO compose模式），如果只设置HTTP_PROXY就不行。 ![截图20240926170240](https://private-user-images.githubusercontent.com/30309355/371064944-6d3271d5-1771-43f3-9256-5f1bbe3fd133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjM5MTUsIm5iZiI6MTcyNzM2MzYxNSwicGF0aCI6Ii8zMDMwOTM1NS8zNzEwNjQ5NDQtNmQzMjcxZDUtMTc3MS00M2YzLTkyNTYtNWYxYmJlM2ZkMTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE1MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTc4MGIxZDUwMTE4ZTJjY2FiZjZkM2E0ZjRkZDJiYmU0ZjlmYTAyY2I1ZTZlZWMxODZmMmFlMjAwYjljYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ibHx7KS3sX0bqUkvaSV3Fa1pdODJvmjkcucQ5gOHEIU)

请问环境变量设置HTTP_PROXY和HTTPS_PROXY值需要怎么填写？

**Comment by lovemikusama** [comment]
> > 环境变量设置HTTP_PROXY和HTTPS_PROXY就可以（我用的mihomo），刚刚测试了（UGOS PRO compose模式），如果只设置HTTP_PROXY就不行。 ![截图20240926170240](https://private-user-images.githubusercontent.com/30309355/371064944-6d3271d5-1771-43f3-9256-5f1bbe3fd133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjM5MTUsIm5iZiI6MTcyNzM2MzYxNSwicGF0aCI6Ii8zMDMwOTM1NS8zNzEwNjQ5NDQtNmQzMjcxZDUtMTc3MS00M2YzLTkyNTYtNWYxYmJlM2ZkMTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE1MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTc4MGIxZDUwMTE4ZTJjY2FiZjZkM2E0ZjRkZDJiYmU0ZjlmYTAyY2I1ZTZlZWMxODZmMmFlMjAwYjljYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ibHx7KS3sX0bqUkvaSV3Fa1pdODJvmjkcucQ5gOHEIU)
> 
> 请问环境变量设置HTTP_PROXY和HTTPS_PROXY值需要怎么填写？

我是用的docker版的mihomo(host模式) 所以填下面的
host 模式两项都输入 http://127.0.0.1:端口 
bridge模式两项都输入 http:/nas 的ip:端口

我的代理端口是7890 用的这个配置：
``` yaml
services:
  dockercopilot:
    container_name: dockercopilot
    restart: always
    network_mode: host
    ports:
      - 12712:12712
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DelOldContainer=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - secretKey=你的登录密码
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
    image: 0nlylty/dockercopilot:UGREEN
    privileged: true
```
